POST http://localhost:3000/login/ 
Content-Type: application/json 

{
  "username":"JoeBiden",
  "password":"biden@123"
}
###

GET  http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4MjYxNDkyM30.KQw0BUtLwJeCly8LHM4Ro7yRt4aU03POaAt874-UqIg
###


GET  http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4MjYxNDkyM30.KQw0BUtLwJeCly8LHM4Ro7yRt4aU03POaAt874-UqIg
###


GET  http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4MjYxNDkyM30.KQw0BUtLwJeCly8LHM4Ro7yRt4aU03POaAt874-UqIg
###

GET  http://localhost:3000/tweets/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4MjYxNDkyM30.KQw0BUtLwJeCly8LHM4Ro7yRt4aU03POaAt874-UqIg
###

GET  http://localhost:3000/tweets/2/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4MjYxNDkyM30.KQw0BUtLwJeCly8LHM4Ro7yRt4aU03POaAt874-UqIg
###


GET  http://localhost:3000/tweets/2/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4MjYxNDkyM30.KQw0BUtLwJeCly8LHM4Ro7yRt4aU03POaAt874-UqIg
###


GET  http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4MjYxNDkyM30.KQw0BUtLwJeCly8LHM4Ro7yRt4aU03POaAt874-UqIg
###


POST  http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4MjYxNDkyM30.KQw0BUtLwJeCly8LHM4Ro7yRt4aU03POaAt874-UqIg
Content-Type: application/json

{
   "tweet": "The Mornings..."
}

###

DELETE  http://localhost:3000/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4MjYxNDkyM30.KQw0BUtLwJeCly8LHM4Ro7yRt4aU03POaAt874-UqIg
###